init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
version: 1.0.{build}
before_build:
- cmd: dotnet restore
build_script:
- cmd: dotnet build .\src\Remote.Linq.EntityFramework\ .\test\Remote.Linq.EntityFramework.Tests\
test_script:
- cmd: dotnet test .\test\Remote.Linq.EntityFramework.Tests\
build:
  verbosity: normal